name = "ex-1"
main = "./index.js"
compatibility_date = "2024-10-11"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "ex2"
database_id = ""

