services:
  example:
    network_mode: host
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: "development"
      CLOUDFLARE_API_TOKEN: ${CLOUDFLARE_API_TOKEN}
    volumes:
      [.:/app] # Monta la directory corrente per aggiornamenti dinamici del codice
    command: sh -c "npm run example"  # 
  ex1:
    network_mode: host
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: "development"
      CLOUDFLARE_API_TOKEN: ${CLOUDFLARE_API_TOKEN}
    volumes:
      [.:/app] # Monta la directory corrente per aggiornamenti dinamici del codice
    command: sh -c "npm run ex1"  # 
  ex2:
    network_mode: host
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: "development"
      CLOUDFLARE_API_TOKEN: ${CLOUDFLARE_API_TOKEN}
    volumes:
      [.:/app] # Monta la directory corrente per aggiornamenti dinamici del codice
    command: sh -c "npm run ex2"  # 
  ex3:
    network_mode: host
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: "development"
      CLOUDFLARE_API_TOKEN: ${CLOUDFLARE_API_TOKEN}
    volumes:
      [.:/app] # Monta la directory corrente per aggiornamenti dinamici del codice
    command: sh -c "npm run ex3"  # 