services:
  sde:
    network_mode: host
    container_name: sde
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: "development"
      CLOUDFLARE_API_TOKEN: ${CLOUDFLARE_API_TOKEN}
    volumes:
      [.:/app] # Monta la directory corrente per aggiornamenti dinamici del codice
    stdin_open: true 
    tty: true