name = "ex-1"
main = "../src/ex2/index.js"
compatibility_date = "2024-10-11"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "ex2"
database_id = "3ff3cf80-4db3-4444-aa06-2b12a3358924"
